package.json, src/lib/app/app.html
Agrego un ngIf que chequea que userInfo tenga organización.
=> appComponent chequeo que userInfo tenga organizacion

src/lib/tabs/tab.component.ts
por problemas de estilo se cambia la estructura de los plex-tab
=> saco div y el ngIf se ubica en el tag ng-content por problemas de estilo

package-lock.json, package.json, src/demo/app/modal/modal.component.ts, src/demo/app/modal/modal.html, src/lib/core/service.ts, src/lib/css/modals.scss
Esta actualización aplica los estilos nativos de Plex y design guidelines al componente modal, que aun conservaba el estilo por defecto de SweetAlert2.
- Permite configurar los textos de las acciones de los botones Confirm/Cancel
- Introduce el uso de parámetros a través un objeto (opcional, con compatibilidad hacia atrás)
- El botón de acción (Confirm) ahora se ubica a la derecha
- Se actualizó la Demo del componente para reflejar los cambios
=> Styling modals

src/lib/button/button.component.ts
Soluciona el problema del click bubbling
=> plex-button bubbling fix

src/lib/css/layout.scss, src/lib/css/plex-box.scss
Aplica hacks para solucionar el problema de plex-layout & plex-box en Firefox, donde el contenido el plex-box no tiene el scroll (overflow: auto) ya que no calcula el height adecuadamente
=> Improve Firefox compatibility with flex

package-lock.json, package.json, src/demo/app/app.module.ts, src/demo/app/header-paciente/header-paciente.component.ts, src/demo/app/header-paciente/header-paciente.html, src/demo/app/header-paciente/header-paciente.scss, src/demo/app/home/home.component.ts, src/demo/app/templates/template-busqueda.ts, src/demo/app/templates/template-form-sidebar.ts, src/lib/app/app.component.ts, src/lib/core/service.ts, src/lib/css/nav.scss
- Se agrega funcionalidad para renderizar una componente en el navbar. 
- Se pasa la componente por Referencia y sus parámetros.
- Método para limpiar el navbar.
- Ejemplo sencillo con header paciente.
=> Navbar: item dinámico

package-lock.json, package.json, src/demo/app/tabs/tabs.component.ts, src/demo/app/tabs/tabs.html, src/lib/css/plex-tabs.scss, src/lib/tabs/tab.component.ts, src/lib/tabs/tabs.component.ts
Agrega estilos a los plex-tabs y la posibilidad de darle colores.
=> plex-tabs- implementa colores para tabs

package-lock.json, package.json, src/lib/select/select.component.ts
Limpia plex-select si se setea en null la variable en ngModel.
=> plex-select: clear options on null ngModel

src/demo/app/accordion/accordion.html, src/demo/app/bool/bool.html, src/demo/app/box/box.html, src/demo/app/datetime/datetime.html, src/demo/app/float/float.html, src/demo/app/int/int.html, src/demo/app/loader/loader.html, src/demo/app/modal/modal.html, src/demo/app/phone/phone.html, src/demo/app/ribbon/ribbon.component.ts, src/demo/app/ribbon/ribbon.html, src/demo/app/select/select.html, src/demo/app/text/text.html, src/lib/css/variables.scss
- Se actualiza HTML de la demo con el nuevo plex-layout/plex-layout-main
- Además se fuerza que los textos de los `<label>` comiencen con mayúsculas
=> Plex demo layout

package-lock.json, package.json, src/demo/app/home/home.html, src/lib/css/plex-title.scss, src/lib/directives/justify.directive.ts, src/lib/directives/responsive.directive.ts, src/lib/layout/main.component.ts, src/lib/layout/sidebar.component.ts, src/lib/module.ts, src/lib/styles.scss, src/lib/title/title.component.ts
- Agrega componente `plex-title`.
- Agrega directiva `justify`.
- Agrega directiva Responsive
=> feat(plex-title): Agrega componente plex-title

package-lock.json, package.json, src/lib/css/plex-help.scss
* Para contenidos extensos se utiliza scroll dentro del panel.
* Se ajustan estilos para mejorar posicionamiento
=> feat(plex-help): se limita el alto del contenedor y el resto se scrollea

src/demo/app/home/home.html, src/lib/css/plex-item.scss, src/lib/css/plex-modal.scss, src/lib/icon/icon.component.ts, src/lib/item-list/list.component.ts, src/lib/modal/modal-title.component.ts, src/lib/modal/modal.component.ts, src/lib/module.ts, src/lib/styles.scss
Se aplican mejoras para que sea más genérico y adaptable. Botón "cerrar" opcional,.
=> Plex modal

.circleci/config.yml, src/demo/app/home/home.html, src/lib/badge/badge.component.ts, src/lib/css/layout.scss, src/lib/css/plex-badge.scss, src/lib/icon/icon.component.ts
**plex-icon**: agrega propiedad prefix para usar la font de Andes.
**plex-icon**: agrega propiedad size.
**plex-badge**: agrega propiedad color para colores dinámicos. (los tipos básicos siguen siendo útiles).
=> plex-icon y plex-badge

src/lib/css/mixins/scrollbar.scss, src/lib/css/nav.scss, src/lib/css/plex-box.scss, src/lib/styles.scss
Agrega scrollbar al menú hambuerguesa.
=> feat(plex-app): add scroll to nav menu

.circleci/config.yml, src/demo/app/app.component.ts, src/demo/app/app.module.ts, src/demo/app/app.routes.ts, src/demo/app/detail/detail.component.ts, src/demo/app/detail/detail.html, src/demo/app/home/home.html, src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts, src/lib/directives/responsive.directive.ts, src/lib/module.ts, src/lib/styles.scss
Componente para visualizar detalle de pacientes y registros en general.
=> plex-detail

package-lock.json, package.json, src/demo/app/home/home.html, src/demo/app/item-list/item-list.component.ts, src/demo/app/item-list/item-list.html, src/lib/css/layout.scss, src/lib/css/plex-box.scss, src/lib/css/plex-item.scss, src/lib/css/variables.scss, src/lib/item-list/heading.component.ts, src/lib/item-list/item.component.ts, src/lib/item-list/list.component.ts, src/lib/module.ts
- Ajustes visuales
- scroll infinito
=> plex-list: ajustes visuales y scroll infinito

src/demo/app/home/home.component.ts, src/demo/app/home/home.html, src/lib/css/plex-help.scss, src/lib/help/help.component.ts
1. Ahora tiene posición absoluta (flota sobre el contenido)
2. Se integra con plex-title
=> feat(plex-help): ahora flotante, mejor integrado a plex-title

index.ts, src/lib/module.ts, src/lib/options/options.component.ts
Agrega componente plex-options
=> feat(plex-options): componente plex-options

src/demo/app/home/home.component.ts, src/demo/app/home/home.html, src/lib/css/plex-visualizador.scss, src/lib/module.ts, src/lib/styles.scss, src/lib/visualizador/preview.directive.ts, src/lib/visualizador/visualizador.component.ts
1. Incorpora componente `plex-visualizador`. Preview de imagenes en tamaña grande.
2. Directive `preview`: al hacer click en una imagen se crea automáticamente un `plex-visualizador` y muestra la imagen en grande.
=> Plex visualizador

src/demo/app/detail/detail.html, src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts
Se generaba un espacio en el contenedor de los datos secundarios
=> fix(plex-detail): se resuelve espacio indeseado cuando no hay imagen

src/demo/app/app.component.html, src/lib/app/app.component.ts, src/lib/app/nav-item.component.ts, src/lib/css/nav.scss, src/lib/css/plex-help.scss, src/lib/help/help.component.ts, src/lib/module.ts
Se crea la posibilidad de tener custom items en la navbar
=> Custom nav-item en la navbar

src/demo/app/dropdown/dropdown.component.ts, src/demo/app/dropdown/dropdown.html, src/lib/dropdown/dropdown.component.ts
- Se agrega el valor 'sm' a la propiedad size del componente
- Se modifica demo del componente en plex para mostrar opciones y casos de uso
=> feat(plex-dropdown):se agrega propiedad size

.circleci/config.yml
=> chore(circleci): set applitool branch name

src/demo/app/app.component.ts, src/demo/app/app.module.ts, src/demo/app/app.routes.ts, src/demo/app/templates/listado-sidebar/listado-sidebar.html, src/demo/app/templates/listado-sidebar/listado-sidebar.ts, src/demo/app/templates/templates.scss, src/demo/app/wrapper/wrapper.component..ts, src/demo/app/wrapper/wrapper.html, src/lib/css/plex-wrapper.scss, src/lib/directives/grow.directive.ts, src/lib/module.ts, src/lib/phone/phone.component.ts, src/lib/styles.scss, src/lib/wrapper/wrapper.component.ts
Se agrega una componente que organiza los elementos de un formulario/filtros.
=> feat(plex-wrapper): implementa componente contenedora

src/demo/app/home/home.html, src/lib/css/tooltip.scss, src/lib/styles.scss, src/lib/tooltip/tooltip-content.component.ts
=> feat(tooltip): Soporte multilínea para textos largos

src/demo/app/wrapper/wrapper.html, src/lib/css/plex-wrapper.scss
=> fix(plex-wrapper): se aplica ellipsis en 75% del ancho

src/demo/app/button/button.html, src/lib/app/app.component.ts, src/lib/css/classes.scss, src/lib/css/layout.scss, src/lib/css/nav.scss, src/lib/css/plex-badge.scss, src/lib/css/plex-box.scss, src/lib/css/plex-button.scss, src/lib/css/plex-dropdown.scss, src/lib/css/plex-help.scss, src/lib/css/plex-text.scss, src/lib/css/variables.scss
- Se redujo globalmente el tamaño de la font, pasando el tamaño xs a ser el tamaño base. 
- Se adaptaron botones y badges.
- Se redujo en 5 px el ancho de las "calles" entre contenedores principales (main, sidebar y footer).
- Se redujo de 1.5 a 1.35 el alto de línea en algunos componentes.
- No se hicieron cambios que afecten manera de funcionar de ningún componente.
=> feat(plex): Reducción global de cuerpo tipográfico y relacionados

src/lib/css/nav.scss
Se detectó un problema en el posicionamiento de algunos elementos en la barra principal de la app, en ciertos contextos, se aplicó un fix.
=> fix(nav-actions): se fuerza posición de .action en nav

src/lib/css/nav.scss
Se eliminó posicionamiento con floating divs, lo cual soluciona que no se visualizaba
=> fix(loader): se arregla posicionamiento de loader en navbar

src/demo/app/templates/componentes/plex-modal-template/plex-modal-template.html, src/demo/app/templates/componentes/plex-modal-template/plex-modal-template.ts, src/demo/app/templates/listado-sidebar/listado-sidebar.html, src/demo/app/templates/listado-sidebar/listado-sidebar.ts, src/lib/modal/modal.component.ts
Opciones para habilitar/deshabilitar el cierre del modal haciendo haciendo click afuera y con la tecla esc.
=> plex-modal: allowBackdropClose y allowEscClose

src/demo/app/bool/bool.html, src/lib/css/layout.scss
- Se agrega propiedad 'background: white' al checkbox
- Se anida estilo bajo tag <plex-layout-sidebar>
=> fix(plex-bool): se corrige visualización en invert

cypress/integration/select.js, src/demo/app/templates/listado-sidebar/sidebar/detalle/sidebar-detalle.component.html, src/demo/app/templates/listado-sidebar/sidebar/detalle/sidebar-detalle.component.ts, src/lib/options/options.component.spec.ts, src/lib/options/options.component.ts
Detectar si cambian los items y si es así seleccionar el primero si el anterior seleccionado desaparecio. Usar la interfaz OnChange de Angular.
=> feat(plex-options): agrega ngOnChanges en plex options

cypress/integration/navbar.js, src/demo/app/app.component.ts, src/demo/app/app.module.ts, src/demo/app/app.routes.ts, src/demo/app/home/home.html, src/demo/app/navbar/navbar.html, src/demo/app/navbar/navbar.ts, src/lib/app/app.component.ts, src/lib/core/service.ts, src/lib/css/layout.scss, src/lib/css/variables.scss
Hace lo que dice.
Se puede activar desde el sidebar con el botón
=> feat(nav-bar): opción para ocultar nav principal

cypress/integration/wrapper.js, src/lib/directives/grow.directive.ts
La directiva grow no andaba bien con nombres de variables que sean numeros.
=> plex-wrapper: directiva grow

cypress/integration/text.js, cypress/support/plex.js, src/demo/app/text/text.component.ts, src/demo/app/text/text.html, src/lib/css/plex-text.scss, src/lib/text/text.component.ts, src/lib/validation-messages/validation-messages.component.ts
https://proyectos.andes.gob.ar/browse/PLEX-74
- usa validador de pattern de Angular
- se implementa mensaje de error customizado
- se agregaron tests para esta funcionalidad y otros casos de uso de plex-text
- boy scout: se corrigió posicionamiento de mini botón "clear" que limpia el campo de texto
=> feat(plex-text): type="email"

src/demo/app/item-list/item-list.html, src/demo/app/templates/listado-sidebar/main/listado/main-listado.component.html, src/demo/app/templates/listado-sidebar/sidebar/detalle/sidebar-detalle.component.html, src/lib/css/plex-item.scss, src/lib/item-list/heading.component.ts, src/lib/item-list/item.component.ts, src/lib/item-list/list.component.ts
A partir de la incorporación de la directiva responsive:
- Se agregan las clases pertinentes para lograr apilamiento de elementos en item
- Se oculta heading al ocurrir apilamiento (el componente pierde naturaleza de tabla)
=> PLEX: se adapta plex-item a modo responsive

src/lib/hint/hint.component.ts, src/lib/hint/hint.directive.ts
Se cambia la detección de cambios de AfterViewInit a OnInit en directiva hint
=> fix(hint): change detection OnInit

cypress/integration/tabs.js, src/demo/app/tabs/tabs.html, src/lib/directives/responsive.directive.ts, src/lib/layout/layout.component.ts, src/lib/tabs/tabs.component.ts
Implementa la "nueva api" de los navegadores: **ResizeObserver**. Mejora la performance en la detección del tamaño del contenedor.
=> perf(responsive): implementa ResizeObserver

src/demo/app/dropdown/dropdown.html, src/lib/dropdown/dropdown.component.ts
=> feat(plex-dropdown): permite agregar contenido variable

src/lib/css/hint.scss, src/lib/css/plex-datetime.scss
- Se mejora visualización de hint con action en `<plex-datetime>`
- Se corrige hint flotante en scroll
=> fix(hint): mejoras visuales

src/demo/app/templates/componentes/plex-modal-template/plex-modal-template.html, src/demo/app/templates/componentes/plex-modal-template/plex-modal-template.ts, src/lib/css/plex-modal.scss
<plex-modal> tiene un icon con tamaño especial.
- Ese tamaño se estaba aplicando a otros componentes que tienen icon.
- Se encapsuló ese caso especial para que no haya mala herencia.
=> fix(plex-modal): se encapsula estilo de header

src/demo/app/select/select.component.ts, src/demo/app/select/select.html, src/lib/css/plex-select.scss, src/lib/select/select.component.ts
- fix(plex-select): evita validar si está disabled
- feat(plex-select): ícono ingreso texto en multiple
- feat(plex-select): se actualiza demo (el commit dice plex-text, pero es plex-select)
=> feat(plex-select): mejora visual modo buscador

src/demo/app/bool/bool.html, src/lib/css/plex-bool.scss
=> fix(plex-bool): mejora contraste en sidebar invert

src/demo/app/templates/listado-sidebar/listado-sidebar.html, src/lib/core/service.ts, src/lib/directives/mobile.directive.ts, src/lib/module.ts
Agrega la directiva Mobile, para renderizar elementos dependiendo del tipo de dispositivo
=> Mobile directive

cypress/integration/radio.js, cypress/support/plex.js, src/demo/app/radio/radio.html, src/lib/radio/radio.component.ts
`plex-radio` permite una opción multiple y se transforma en un checkbox
=> feat(plex-radio): permite multiple seleccion

src/demo/app/grid/grid.component.html, src/demo/app/grid/grid.component.ts, src/lib/css/plex-grid.scss, src/lib/grid/grid.component.ts
Requerimiento [PLEX-199](https://proyectos.andes.gob.ar/browse/PLEX-199)
- Se agrega el atributo [noGap] que elimina los espacios entre columnas
- Se extienden sizes 'xs' y 'lg'
- Se agregan los valores de columnas fijas: '5' y '6'
=> feat(plex-grid): extiende sizes y agrega noGap

package-lock.json, package.json, src/lib/core/service.ts, src/lib/layout/layout.component.ts, src/lib/toast/push-notifications/services/push-notifications.service.ts, src/lib/toast/simple-notifications/components/simple-notifications.component.ts, src/lib/toast/simple-notifications/services/notifications.service.ts
quita dependencia molesta de rxjs-compat
=> refactor(rxjs): quita dependencia rxjs-compat

src/lib/accordion/panel.component.ts, src/lib/css/plex-accordion.scss
Se visualiza en la demo de "accordion"
=> feat(accordion): se mejora look and feel en invert

src/demo/app/app.component.ts, src/demo/app/app.module.ts, src/demo/app/app.routes.ts, src/demo/app/table/table.html, src/demo/app/table/table.ts, src/demo/app/templates/service/paciente.service.ts, src/lib/css/plex-item.scss, src/lib/css/plex-table.scss, src/lib/item-list/list.component.ts, src/lib/module.ts, src/lib/styles.scss, src/lib/table/columns.directive.ts, src/lib/table/display-column.directive.ts, src/lib/table/table-column-dropdown.component.ts, src/lib/table/table-sort.pipe.ts, src/lib/table/table.component.ts, src/lib/table/table.interfaces.ts
Agrega nuevo componente **plex-table** con algunas features:
- Auto encolumnado.
- Sort Automatico.
También se aplica a _plex-list_.
=> plex-table

src/demo/app/card/card.component.html, src/lib/css/classes.scss
Se crea la clase global _.disabled_, de modo que sea accesible/utilizable desde cualquier componente PLEX:
- Se agrega en la hoja de estilos classes.scss (src\lib\css\classes.scss)
- Se agrega  caso de uso en plex-card (src\demo\app\card\card.component.html)
=> feat(classes): agrega clase global disabled

src/demo/app/card/card.component.html, src/demo/app/card/card.component.ts, src/lib/card/card.component.ts, src/lib/css/classes.scss, src/lib/css/plex-card.scss
Posibilita customizar los colores del background de las plex-cards.
**Caso de uso:**
Task [PLEX-218](https://proyectos.andes.gob.ar/browse/PLEX-218)
=> feat(plex-card): permite custom colors

src/demo/app/table/table.html, src/demo/app/table/table.ts, src/lib/table/table.component.ts
https://proyectos.andes.gob.ar/browse/PLEX-238
=> feat(table): implementa infinite scroll

src/demo/app/home/home.component.ts, src/demo/app/home/home.html, src/lib/app/app.component.ts, src/lib/core/plex-visualizador.service.ts, src/lib/module.ts, src/lib/visualizador/visualizador.component.ts
Injecta el **plex-visualizador** en el **plex-app** así no hay colisiones de z-index.
=> feat(visualizador): injecta el visualizador de forma global

src/demo/app/app.module.ts, src/lib/core/service.ts, src/lib/module.ts
Sólo eso, para tener nombres propios en títulos bien formateados. #castellano
=> feat(title): aplica TitleCasePipe

src/demo/app/table/table.html, src/demo/app/table/table.ts, src/lib/css/plex-item.scss, src/lib/css/plex-table.scss, src/lib/item-list/list.component.ts, src/lib/table/columns.directive.ts, src/lib/table/table-sort.pipe.ts, src/lib/table/table.component.ts, src/lib/table/table.interfaces.ts
Agrega recurso de filtrado a plex-table
=> feat(plex-table): filtros

cypress/integration/text.js, cypress/support/commands.js, package-lock.json, package.json, src/demo/app/app.component.html, src/demo/app/home/home.html, src/demo/app/text/text.component.ts, src/demo/app/text/text.html, src/lib/css/colors.scss, src/lib/text/text.component.ts, src/lib/validation-messages/validation-messages.component.ts
=> Mensajes de error de campos compatibles con screen reader

src/demo/app/bool/bool.component.ts, src/demo/app/bool/bool.html, src/lib/css/plex-accordion.scss, src/lib/css/plex-badge.scss
- Se actualiza demo en plex-bool con ejemplo similar al gestor de usuario
- Otros lugares donde aparece es el badge de validación en la demo de plex-select y en plex-button
=> Se arregla problema con visualización de plex-icon en ciertas anidaciones

src/lib/css/plex-table.scss, src/lib/css/plex-tabs.scss, src/lib/tabs/tab.component.ts
=> Fixes en plex-tab y plex-table

src/demo/app/accordion/accordion.html, src/lib/accordion/accordion.component.ts, src/lib/datetime/bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.scss
**Task**
https://proyectos.andes.gob.ar/browse/PLEX-286
**Mejora**
Input que permita settear el componente para que solo expanda un panel y cierre el resto.
=> feat(plex-accordion): posibilita toggle alternado

src/demo/app/home/home.html, src/lib/title/title.component.ts
Se suma el atributo type a plex-title.
https://proyectos.andes.gob.ar/browse/PLEX-290
=> PLEX: tipos a plex-title

src/demo/app/ribbon/ribbon.component.ts, src/demo/app/ribbon/ribbon.html, src/lib/css/plex-ribbon.scss, src/lib/ribbon/ribbon.component.ts
- Se reduce el espacio para que no interfiera con plex-tile
=> Se reduce tamaño de plex-ribbon

src/lib/datetime/bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.scss
**REQUERIMIENTO**
https://proyectos.andes.gob.ar/browse/UIUX-341
**FUNCIONALIDAD DESARROLLADA**
1. Se agrega un poco mas de px al max-height para que el boton aceptar siempre esta dentro del contenedor
=> PLEX-DATETIME - Agranda content para botón aceptar

src/lib/card/card.component.ts, src/lib/css/plex-card.scss
**Requerimientos**
https://proyectos.andes.gob.ar/browse/PLEX-312
=> feat(plex-card): Agrega atributo size

src/lib/button/button.component.spec.ts, src/lib/module.ts, src/lib/text/text.component.spec.ts
1. Se modifican los test de button y text por funciones deprecadas.
=> CORE - fix test para acutalizacion angular

src/lib/badge/badge.component.ts, src/lib/css/plex-badge.scss, src/lib/css/plex-item.scss, src/lib/css/plex-tabs.scss
https://proyectos.andes.gob.ar/browse/PLEX-229
=> PLEX-BADGE -  Tipología multilinea

src/lib/css/plex-badge.scss
https://proyectos.andes.gob.ar/browse/PLEX-319
=> PLEX-BADGE - Modifica ancho del plex

src/lib/css/plex-table.scss
**Requerimiento**
https://proyectos.andes.gob.ar/browse/PLEX-256
**Funcionalidad desarrollada**
1.  Si la configuracion de la la columna tiene el atributo right:true, se desalinea la fila con lo demas badge o botones
=> PLEX-TABLE - Badge icons desalineados

src/demo/app/detail/detail.html, src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts
https://proyectos.andes.gob.ar/browse/PLEX-208
- Se agrega botones y dropdown en plex-detail.
- Los botones están configurados para tamaños solamente en sm para que no rompa la estructura del plex-detail
=> PLEX-DETAIL -  Agrega botonera

src/demo/app/app.module.ts, src/lib/css/plex-group.scss, src/lib/group/group-item.component.ts, src/lib/group/group.component.ts, src/lib/styles.scss
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-329
1. Se implementa una botonera con varios tipos de elementos admitidos: plex-badge, plex-button y plex-group-item.
2. Se agrupan los elementos por tipo.
3. Se quita la necesidad de agregar clases para dar estilos y ordenamiento a los botones.
=> PLEX - Implementa botonera agrupada

src/lib/datetime/bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.scss, src/lib/datetime/bootstrap-material-datetimepicker/bootstrap-material-datetimepicker.ts, src/lib/datetime/datetime.component.ts, src/lib/table/table.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-233
1. Se reemplaza el selector de años actual por uno nuevo de tipo wheel, para mayor facilidad de uso.
2. Se quitan las opciones de navegación por flechas de años "siguiente" y "anterior".
=> PLEX - Nuevo selector de años en plex-datetime

src/lib/help/help.component.ts
Corrección tras evaluar nueva versión de PLEX en ANDES APP. 
https://proyectos.andes.gob.ar/browse/PLEX-323
=> PLEX-HELP - corrección para apertura de plex-help

package-lock.json, package.json
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-331
**Versión 8.0.0**
Características y mejoras de la versión:
1. Control de cierre de PLEX-HELP cuando hay scroll
2. Agrega control si existe subtitulo en PLEX-GRID
3. Corrección de ancho del PLEX-BADGE
4. Nueva botonera agrupada PLEX-GROUP
5. Corrección de iconos desalineados en PLEX-TABLE
6. Evitar aperturas de PLEX-HELP simultáneas
7. Selector de transparencias en PLEX-TABLE
8. Agregado de datos extras en PLEX-SELECT
9. Corrección del texto en PLEX-RADIO
=> chore(release): nueva version 8.0.0

src/lib/css/plex-radio.scss
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-341
Modifica estilos en plex-radio para quitar overflow en container
=> PLEX - Modifica error de muestreo en plex-radio

src/lib/help/help.component.ts, src/lib/help/services/help.service.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-339
Se realizan quita el cierre automático al hacer scroll con plex-help abierto
=> PLEX - Modifica cierre automático con scroll en plex-help

src/lib/css/hint.scss, src/lib/css/plex-bool.scss, src/lib/hint/hint.component.ts, src/lib/hint/hint.directive.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-350
- Implementa posicionamiento nuevo en hint y evita ocultamiento dentro de grid
=> Plex-hint - Implementa mejoras en plex-hint

src/lib/help/help.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-349
- Implementa método [closeHelp] de cierre programado
- Modifica controles sobre posicionamiento de help cuando hay scroll en padre
- Modifica posicionamiento inicial de help al cerrar y abrir luego de scroll
=> PLEX-HELP - Implementa mejoras funcionales

package-lock.json, package.json
Versión 8.0.5
PLEX-TEXT - Implementa validación personalizada
PLEX-TEXT - Repara error de vista html en plex-text 
PLEX-HELP - Implementa mejoras funcionales 
PLEX-HINT - Implementa mejoras en plex-hint 
PLEX-HELP - Scroll y maxHeight opcionales en plex-help 
PLEX-BOOL - Corregir overflow en checkbox
=> chore(release): actualiza version a 8.0.5

package-lock.json, package.json
La nueva version incluye:
- Implementación de la librería _ngx-simple-text-editor_ como editor html en plex-text
=> PLEX - Nueva versión 8.0.6

angular.json, package-lock.json, package.json, src/lib/text/text.component.ts
La nueva versión incluye:
1. Incorporación de nuevos iconos para la librería plex-text
=> chore(release): actualiza version a 8.0.7

.github/workflows/build.yml, package-lock.json, package.json, src/lib/text/text.component.ts
- Fix: corrige value en plex-text para evitar _undefined_
=> PLEX - Version 8.0.9

src/lib/core/service.ts
Fix: se realiza un cambio en los colores por defecto de los botones de acción en plex-swal
=> SWAL - Modifica colores de boton por defecto

src/lib/text/text.component.ts
1. Implementa control de formato de texto al pegar contenido en plex-text
2. Implementa opciion de listado con bullets es plex-text
=> PLEX - Implementa control de formato al pegar en editor html

package-lock.json, package.json
1. Se agregan métodos para el seleccionado por rutas de subitems en plex-menu
2. Se agrega opcion para insertar vínculos en plex-text
3. Se corrigen detalles visuales en plex-slider
4. Nueva libreria para plex-help
=> PLEX - Release version 8.0.14
