andes/plex

package.json, src/demo/app/datetime/datetime.component.ts, src/demo/app/home/home.component.ts, src/demo/app/home/home.html, src/lib/core/validator.functions.ts, src/lib/tooltip/tooltip-content.component.ts
Ajuste en la comparación de horas en plex-datetime.  Había un error al comparar el valor actual con la fecha min y max. Se comparava la día y hora, en vez de la hora sola. 
Ver ejemplo en demo.
=> Comparación de hora en plex-datetime

src/demo/app/button/button.html, src/lib/button/button.component.ts
-  Implementa mejora para que plex-button tome como parámetro un NgForm en la propiedad validateForm
Esto permite que un botón fuera del form pueda acceder a la validación. Por ejemplo: el form puede estar dentro del main container y el botón en el footer
=> mejora plex-button validateForm

src/demo/app/text/text.component.ts, src/demo/app/text/text.html, src/lib/text/text.component.ts
Implementa parametro `debounce` en `plex-text`.  Demora la ejecución  del evento `change` en una cierta cantidad de milisegundos para simular la espera al terminado de escribir.
=> agrega opción debounce en plex-text

src/lib/css/plex-box.scss
El layout se rompia en las nuevas versiones de Google Chrome.
=> layout: Ajusta el layout a la nueva version de chrome

src/lib/css/plex-text.scss, src/lib/css/variables.scss
En algunas pantallas los placeholders no se leen.
Se cambió el color de los mismos, dando más contraste y por tanto mejor legibilidad.
=> PLEX - color de placeholders

src/demo/app/datetime/datetime.component.ts, src/demo/app/datetime/datetime.html, src/lib/css/plex-box.scss, src/lib/css/plex-select.scss, src/lib/select/select.component.ts
Se corrigen inconsistencias de plex-select con respecto a otros elementos de formulario:
- La propiedad `border-color` del contenedor de datos era `#f0f0f0` cuando en los demás elementos era `rgba(0, 0, 0, 0.15)`
- La propiedad `line-height` era `1.5` (heredada de body) cuando debería ser `1.25` como los demás elementos (se resetea a `0` para que herede las mismas reglas)
- Se elimina dolor ojos
=> Selectize height

.circleci/config.yml, cypress/integration/datetime.js, cypress/support/plex.js, src/demo/app/datetime/datetime.component.ts, src/demo/app/datetime/datetime.html, src/lib/datetime/datetime.component.spec.ts, src/lib/datetime/datetime.component.ts, src/lib/text/text.component.spec.ts
- Parámetro de tamaño
- Propiedad debounce para evitar request masivos. Espera un tiempo antes de ejecutar el método `change`.
- Propiedad para ocultar el `input`, usar solo el botón para mostrar el calendario.
=> Nuevas funcionalidades de plex-datetime

src/lib/modal/modal.component.ts
Agrega:
1. Evento _closed_ al cerrar el modal.
2. Permite cerrar el modal tocando la tecla Escape.
=> plex-modal: evento closed y tecla escape

src/lib/css/toast.scss, src/lib/css/variables.scss, src/lib/toast/simple-notifications/components/notification.component.ts
Las tostadas :bread: de plex tenían una paleta de colores diferente a la del resto de los componentes, se aplicó la paleta correcta de colores base (success, danger, warning, info).
=> fix(toast): se aplica paleta de colores correcta

src/demo/app/app.component.ts, src/demo/app/app.routes.ts, src/demo/app/button/button.component.ts, src/demo/app/button/button.html, src/lib/badge/badge.component.ts, src/lib/css/plex-badge.scss
Se implementó el uso de íconos y botones adjuntos a un plex-badge;
Ejemplos de uso:
**plex-badge + plex-button**
```
<plex-badge size="sm" type="warning">TEMPORAL
<plex-button icon="clock"></plex-button>
</plex-badge>
```
------
**plex-badge + plex-icon**
```
<plex-badge size="sm" type="success">VALIDADO
<plex-icon name="clock"></plex-icon>
</plex-badge>
```
------
**plex-badge + plex-button + plex-icon**
```
<plex-badge size="sm" type="success">VALIDADO
<plex-icon name="clock"></plex-icon>
<plex-button icon="clock"></plex-button>
</plex-badge>
```
=> Plex-badge con icon y button

src/lib/modal/modal.component.ts
**Problema:**
Un plex-modal se puede cerrar tanto con un botón Cancelar como apretando la tecla ESC, en este úlitmo caso, se detectan eventos de teclado para realizar la acción.
Había un problema con la captura de eventos de teclado, ya que lo hacía de manera global y evitaba que, por ejemplo, se pueda escribir dentro de un plex-text.
**Solución**
Se agregó un control para asegurarse de que la detección de la tecla ESC suceda sólo después de que el usuario ya ingresó un caracter.
=> fix(plex-modal): se agrega control para no bloquear teclas 

src/lib/css/plex-dropdown.scss, src/lib/css/variables.scss
El item seleccionado en un dropdown usaba un color heredado de bootstrap (blue primary) en lugar de usar el blue de la paleta de plex.
Ahora usa el blue default de andes (usado por los componentes con type="info")
=> PLEX: fix(plex-dropdown): estilo active con color de paleta plex

src/demo/app/templates/componentes/plex-filters/plex-filters.component.html, src/lib/core/validator.functions.ts, src/lib/css/forms.scss, src/lib/datetime/datetime.component.ts, src/lib/float/float.component.ts, src/lib/int/int.component.ts, src/lib/phone/phone.component.ts, src/lib/radio/radio.component.ts, src/lib/select/select.component.ts, src/lib/text/text.component.ts
- Actualmente los **label** de diversos elementos de formulario presentan la leyenda _"opcional"_ al no ser campos requeridos. 
- Se elimina dicha leyenda y se propone marcar los requeridos con un asterisco.
[](https://proyectos.andes.gob.ar/browse/PLEX-56)
=> feat(plex): se remueve leyenda opcional y se aplica asterisco a requeridos

src/demo/app/accordion/accordion.html, src/lib/css/plex-accordion.scss, src/lib/css/variables.scss
- Se transparenta background de componente para correcta visualización sobre fondo oscuro (invert)
- Se cambia color de bordes a blanco para su visualización en <plex-layout-sidebar type="invert">
- Se modifica demo para ver caso de uso
=> fix(plex-accordion):visualización invert

src/demo/app/datetime/datetime.component.ts, src/demo/app/datetime/datetime.html, src/lib/badge/badge.component.ts, src/lib/css/plex-badge.scss
Actualmente en un `plex-badge` pueden incluirse un `plex-button` o un `plex-icon` (o ambos), ahora se agregó soporte para `plex-datetime`:
```javascript
let myModel = {
fecha: moment(),
};
```
```html
<plex-badge size="sm" type="warning">
{{ myModel.fecha | date: 'dd/MM/yyyy' }}
<plex-datetime type="date" [(ngModel)]="myModel.fecha" name="onlybtn" [btnOnly]="true" size="sm"></plex-datetime>
</plex-badge>
```
=> feat(plex-badge): soporte para plex-datetime

src/demo/app/tabs/tabs.html, src/lib/css/plex-tabs.scss, src/lib/tabs/tabs.component.ts
Se aplicó una mejora de visualización para espacios reducidos cuando los tabs usan la opción size="full" y algún tab sólo tiene icono y no tiene label.
Ver adjunto:
=> feat(plex-tab): Se optimiza uso de espacio de tab cuando tiene ícono

src/demo/app/home/home.html, src/lib/css/plex-help.scss
El uso de `width: max-content` en plex-help **causa un problema** en la ventana flotante, haciendo que sea del ancho máximo que el contenido puede tener, lo cual trae problemas si el contenido es muy ancho, especialmente en resoluciones bajas (generalmente en monitores viejos o pequeños).
**Se solucionó** aplicando `width: auto`. Se descartó usar `fit-content` porque da un resultado demasiado ajustado.
=> fix(plex-help): se corrige overflow de contenido en resoluciones bajas

cypress/integration/detail.js, src/demo/app/detail/detail.html, src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts
**Problema:**
Al reducirse el tamaño de alguno de los elementos que componen el contenedor principal (título, subtítulo e imágen), el contenedor de los labels se "pega" al principal. 
**Solución:**
Se le asigna un valor de 1rem al márgen inferior de la imágen/icono
**Tareas scout:**
- Se alinean los badge al centro en la disposición 'column' (en un plex-help por ejemplo, antes se alineaban a la izq. > valor por defecto de flex)
- Se agrega 'background' a la línea divisora (antes presentaba un calado interno al tener sólo 'border')
=> fix(plex-detail):se corrige margen e/ info principal y labels

src/lib/css/plex-select.scss
Se actualizó el icon que se muestra durante la carga de datos async de un plex-select.
=> fix(plex-select): nuevo hex value de loading icon

src/lib/app/app.component.ts
Actualmente el menú principal consta de un <div> con un evento (click) de Angular, por lo que es posible que lectores de pantalla tengan dificultad para leerlo/encontrarlo.
Se agregaron attributes de HTML para indicar tabindex y role="button" para el item que abre el menú principal de la aplicación.
Se realiza este cambio apuntando a arreglar y mejorar la navegación con dispositivos lectores de pantalla, por ejemplo, para personas no videntes.
=> fix(tabindex): se agrega tabindex y role al menú

cypress/integration/tooltip-hint.js, cypress/support/plex.js, src/demo/app/app.component.ts, src/demo/app/app.module.ts, src/demo/app/app.routes.ts, src/demo/app/home/home.html, src/demo/app/tooltip-hint/tooltip-hint.component.ts, src/demo/app/tooltip-hint/tooltip-hint.html, src/lib/css/hint.scss, src/lib/css/mixins/_position.scss, src/lib/css/nav.scss, src/lib/css/plex-title.scss, src/lib/css/tooltip.scss, src/lib/hint/hint.component.ts, src/lib/hint/hint.directive.ts, src/lib/icon/icon.component.ts, src/lib/module.ts, src/lib/styles.scss, src/lib/title/title.component.ts, src/lib/tooltip-hint/tooltip-hint.component.ts, src/lib/tooltip-hint/tooltip-hint.directive.ts, src/lib/tooltip/tooltip.component.ts
Este tooltip no "compite" con el tooltip actual, con lo cual se podría simplemente reemplazar todas las ocurrencias de `title=""` y `[title]="" `en todas las apps que usen Plex.
=> feat(tooltip): se activa tooltip de material

src/lib/css/plex-options.scss, src/lib/options/options.component.ts, src/lib/styles.scss
- Se flexea el contenedor de los la botonera interna del componente
- Se aplica un 'grow: 1' para lograr equidad de anchos y comportamiento full en caso de botón huérfano.
=> feat(plex-options): se agregan clases para comportamiento responsivo

src/lib/css/plex-detail.scss, src/lib/css/plex-help.scss, src/lib/css/plex-title.scss, src/lib/css/plex-wrapper.scss, src/lib/directives/responsive.directive.ts, src/lib/title/title.component.ts
Se implementa una versión responsive inicial de plex-title.
Básicamente acomoda el título en una línea inicial, y el agrupamiento de elementos (botones, badges, etc) en la línea siguiente, con las siguientes reglas:
- El título se mantiene alineado a la izquierda
- Lo botones y elementos pasan de estar alineados a la derecha a tener la regla "space-between" de justificado de flex.
=> feat(plex-title): modo responsive de botonera

src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts
**Problema:**
El contenedor donde se alojaba el nombre completo del paciente no tenía un valor asignado en la propiedad 'width'. Por lo que tomaba el valor 'auto', heredando el ancho máximo de su contenedor padre (de muy reducido tamaño).
**Solución**
Settear un valor 'fit-content' al contenedor e incluir un wrap para que los textos no excedan el ancho de su contenedor en pantallas reducidas.
=> fix(plex-detail): se define ancho de nombres y wrapean los badges

src/demo/app/text/text.html, src/lib/text/text.component.ts
Solo se podía setear una altura en __px__. Ahora se puede pasar la unidad en el mismo valor. Depende del tipo del parametro.
=> Plex text height

src/lib/app/app.component.ts
El lector de pantallas para no videntes no lee los elementos ocultos. No sabemos si se actualizo el lector, si cambio plex o si cambio google chrome. Pero al estar ocultos no se pueden navegar con el tab.
Se agrega control de teclas para abrir el menú del navbar.
=> feat(navbar):  desplegar menu con enter

src/demo/app/templates/listado-sidebar/listado-sidebar.html, src/lib/css/plex-box.scss, src/lib/wrapper/wrapper.component.ts
**Problema**
Al aparecer el scrollbar, modifica el ancho del contenedor de los inputs y genera reconfiguración de los elementos.
**Solución**
Se cambia valor asignado al scroll, de 'auto' a 'overlay'; de éste modo, al aparecer el scrollbar no 'empuja' los elementos (inputs) hacia adentro provocando su reordenamiento y consecuente apilamiento (al estar el ancho cercano a un breakpoint).
=> fix(plex-wrapper): se settea scrollbar en overlay

src/lib/css/plex-item.scss, src/lib/item-list/item.component.ts
**Problema:**
Para evitar desfase de heading respecto a columnas de listado cuando no había botones se incorporaban elementos HTML vacíos en el heading para compensar espacio y lograr el alineamiento de las columnas.
**Solución**
Se asignó un valor de ancho tanto al heading como al listado de modo que siempre coinciden los elementos independientemente de la existencia de una botonera.
=> fix(plex-item): se agrega versión sin botonera

src/lib/css/tooltip.scss
El tooltip tenía algunos problemas al heredar el tipo de display del contenedor padre del elemento que tiene al mismo (al tooltip).
Se aplicó `display: flex;` para forzar que siempre se muestre de esta manera, evitando problemas de alineamiento en distintas anidaciones.
=> fix(tooltip): display flex para evitar pesada herencia de display

src/demo/app/templates/listado-sidebar/listado-sidebar.html, src/demo/app/templates/listado-sidebar/listado-sidebar.ts, src/lib/css/layout.scss, src/lib/layout/layout.component.ts
**1. Cómo funciona?**
Mediante la inyección de dos propiedades CSS:
a. focused (flexea el panel acaparando el 100% del ancho)
b. not-focused (fuerza un display: none)
=> feat(layout-responsive): permite secuenciar el layout en responsive 

src/demo/app/wrapper/wrapper.html, src/lib/css/plex-wrapper.scss, src/lib/directives/grow.directive.ts
**Problema:**
El input plex-int no formaba parte de la hoja de estilos del plex-wrapper, causando que no adquiera propiedades heredadas del mismo (margins, alineamiento, etc.).
**Solución:**
Se agrega plex-int en la hoja de estilos del plex-wrapper
**Plus:** se cambia nombre de clase de la directiva 'grow' de '.grid-columns-span-n' a '.grow-n'
=> fix(plex-wrapper): agrega plex-int como elemento del componente

src/demo/app/item-list/item-list.component.ts, src/demo/app/item-list/item-list.html, src/lib/css/plex-grid.scss, src/lib/css/plex-item.scss
**Problema:**
Los anchos de los inputs presentes en el plex-item no respondían a la grilla interna.
**Solución**
Se los incorpora a la hoja de estilo del componente y se les setea un width y un min-width (que se corresponde con el valor mínimo que adquiere la celda de la grilla).
**Captura del problema**
**Captura de la solución**
=> fix(plex-item): corrige ancho de inputs y desacopla directiva span del grid

src/demo/app/tabs/tabs.component.ts, src/demo/app/tabs/tabs.html, src/lib/module.ts, src/lib/tabs/pl-tab.directive.ts, src/lib/tabs/tab.component.ts, src/lib/tabs/tabs.component.ts
Permite carga de forma asyncrona el contenido de una tab. Dos alternativas:
1. Cuando el usuario hace click en la tab, el contenido recién ahí se renderiza.
2. Indicar un tiempo de gracias, pasado ese tiempo se renderiza el contenido (no quiere decir que se muestre).
**Motivaciones**:
Hay tabs de pocos usos que hacen llamados al servidor. La idea es evitar esos llamados o que no se encolen con los request principales de la pantalla.
=> Directiva plTab

src/demo/app/button/button.html, src/lib/badge/badge.component.ts, src/lib/css/plex-badge.scss
Se agrega valor 'block' para que el badge se comporte en concordancia con el plex-button y lograr casos como el siguiente:
=> feat(plex-badge): se agrega valor block a la propiedad size

src/lib/select/select.component.ts
No se podía setear como valor inicial un array de opciones, en el caso de select multiples
=> fix(plex-select): valor inicial multiple

src/demo/app/tooltip-hint/tooltip-hint.component.ts, src/demo/app/tooltip-hint/tooltip-hint.html, src/lib/hint/hint.component.ts
El hint usa funcionalidad (click) del elemento padre:
- `<span hint="actualizar" (click)="actualizar()>Hola Mundo Plano!</span>`
El ejemplo anterior mostrará un texto con un hint, el cual ejecutará actualizar() al ser clickeado.
=> feat(hint): permite hint clickeable

cypress/integration/tabs.js, src/demo/app/tabs/tabs.component.ts, src/demo/app/tabs/tabs.html, src/lib/css/plex-tabs.scss, src/lib/tabs/tabs.component.ts
Se permite la posibilidad de incluir tanto plex-badge como plex-button al mismo nivel de los tabs.
**Tarea boyscout:** Se invierte color de línea base de tabs para uso invert.
=> feat(plex-tabs): posibilita convivencia con badge y button

src/lib/hint/hint.component.ts, src/lib/hint/hint.directive.ts
2 fixes
- ExpressionChangedAfterItHasBeenCheckedError al iniciar una página que contiene un hint
- Se quita uso de $event, ya que no existe cuando el hint no tiene ningún $event...
=> fix(hint): change detection para evitar error al iniciar + click vacío

cypress/integration/template-listado.js, package-lock.json, package.json, src/demo/app/bool/bool.html, src/lib/css/hint.scss, src/lib/css/mixins/_generic.scss, src/lib/css/plex-bool.scss, src/lib/css/plex-datetime.scss, src/lib/css/plex-item.scss, src/lib/css/plex-radio.scss, src/lib/css/variables.scss, src/lib/styles.scss
- Se corrigió un problema de plex-bool con labels largos, permitiendo al texto fluir en renglones 
- Se agregó efecto :hover para facilitar la comprensión de cual item se selecciona
- Se incorporó la paleta de Andes, saldando una deuda cromática de larga data
- Se corrigió la altura, el cuerpo tipográfico y la alineación entre checkbox/slider y label
- Ver demo en /bool y /item
=> feat(plex-bool): comportamiento inline

src/demo/app/wrapper/wrapper.html, src/lib/css/plex-wrapper.scss, src/lib/title/title.component.ts
Se agregan dos selectores dentro del plex-title para permitir convivencia ordenada con plex-wrapper y plex-tabs.
=> feat(plex-title): permite agregar wrapper y tabs

cypress/integration/detail.js, cypress/integration/help.js, cypress/integration/template-listado.js, src/demo/app/help/help.html, src/demo/app/home/home.html, src/demo/app/item-list/item-list.html, src/lib/app/nav-item.component.ts, src/lib/css/plex-box.scss, src/lib/css/plex-help.scss, src/lib/css/plex-hint.scss, src/lib/css/plex-title.scss, src/lib/css/plex-wrapper.scss, src/lib/help/help.component.ts, src/lib/layout/main.component.ts, src/lib/layout/sidebar.component.ts, src/lib/styles.scss, src/lib/wrapper/wrapper.component.ts
Se "mergearon" los tipos info y help, ahora con diferencias mínimas:
- Los types ("help" o "info") determinan el ícono que los identifica
- Sólo el tipo "info" soporta subtítulo
Se incorporó funcionalidad para optimizar tamaño:
- cardSize ("full" o "half") posibilita ocupar sólo el 50% del ancho si el contenido es reducido.
Además se corrigieron los siguientes problemas:
- Posicionamiento de la ventana/botón toggle
- Falla al visualizar el contenido en modo invert (sidebar)
=> plex-help, revisión visual y funcional

src/demo/app/detail/detail.html, src/lib/css/layout.scss, src/lib/css/plex-detail.scss, src/lib/detail/detail.component.ts
- Se agrega plex-grid para distribuir los datos secundarios (plex-labels) del componente
- Ajustes de alineamiento de textos
- Se corrige el ancho del contenedor del dato principal en disposición 'column' para evitar efecto indeseado (ver adjunto)
=> feat(plex-detail): agrega plex-grid interno

src/demo/app/item-list/item-list.component.ts, src/demo/app/item-list/item-list.html, src/lib/accordion/panel.component.ts, src/lib/css/layout.scss, src/lib/css/plex-box.scss, src/lib/css/plex-item.scss, src/lib/hint/hint.component.ts, src/lib/item-list/item.component.ts, src/lib/item-list/list.component.ts, src/lib/layout/sidebar.component.ts
- Por defecto, los items son "seleccionables" (efecto hover + select), ahora además permite desde el `Input() selectable: true | false `indicar si no deben ser seleccionables
- También se expandió el contenedor de badges para situaciones de pantalla chica (by @JSantarelli)
=> feat(plex-item): opcional seleccionable

src/lib/card/card.component.ts, src/lib/css/plex-card.scss, src/lib/css/plex-grid.scss
**plex-grid:**
- Se cambia valor del height de celdas a 100% (para lograr equidad en los altos).
- Se corrige anidación de propiedades para evitar herencia de estilos en las imágenes.
**plex-card:**
- Se permite contenido libre <ng-content> antes restringido a plex-badge, plex-button y plex-label.
- Se realizan ajustes en la distribución de estos elementos (margin, justify).
Estos fixes surgen para cubrir necesidades detectadas en la creación del componente [shared-galeria-archivos](https://github.com/andes/app/tree/PLEX-180)
Para testear bajarse la rama [PLEX-180](https://github.com/andes/app/tree/PLEX-180) de la app y apuntar a está rama reinstalando Plex (npm i andes/plex#PLEX-180)
=> fix(plex-grid/plex-card): ajusta celdas, extiende elementos en card 

src/lib/card/card.component.ts, src/lib/css/layout.scss, src/lib/css/mixins/cardBackground.scss, src/lib/css/plex-card.scss
**FIXES:**
**plex-layout:**
- Se restringe la animación del layout mediante el atributo` [reizable]="true"`.
**plex-card:**
- Se reordenan los elementos internos.
- Se agrega espaciado y flex al `<ng-content>`.
- Se agrega la posibilidad de marginar elementos hacia la derecha.
=> fix(layout/card): restringe animation, reordena contenido 

src/lib/directives/aligned.directive.ts, src/lib/module.ts
- Es una directiva que permite alinear los elementos en el eje vertical de un determinado espacio.
- Es el equivalente a 'align-items' de flex y sus respectivos valores (center, start y end), tomando por defecto 'center'.
- Evita que el desarrollador deba escribir un conjunto de clases sintetizándolas en un selector [aligned].
- Se emplea aplicando la directiva al tag que envuelve uno o varios elementos hijos.
=> feat(aligned): crea directiva

src/lib/tabs/tabs.component.ts
Permite cerrar un tab con la rueda del mouse.
También pone un condicional porque en RUP esta pinchando la tab:
```
TypeError: Cannot set property 'active' of undefined
at i.doActiveTab (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:527856)
at https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:527615
at u.invokeTask (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:2049454)
at Object.onInvokeTask (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:466227)
at u.invokeTask (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:2049375)
at a.runTask (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:2044863)
at invokeTask (https://app.andes.gob.ar/main-es2015.4a85d8ef0e621750e050.js:1:2050504)
at invoke …
```
=> feat(tab): close tab with mouse wheel

src/lib/css/tooltip.scss
Se cambia la opacidad del contenedor del tooltip de .7 a .85﻿
=> feat(tooltip): se incrementa opacity de contenedor

src/demo/app/item-list/item-list.component.ts, src/demo/app/item-list/item-list.html, src/lib/css/plex-item.scss, src/lib/item-list/item.component.ts
Asigna un esquema de color a un item, usando 3 propiedades:
1. `background`
2. `border`
3. `hover` border durante el evento _hover_
Funciona a través de un `@Input() colors` que espera el siguiente formato:
```
misColores = {
border: '#b0cfa0',
hover: '#80b266',
background: '#e9f2e5'
};
...
<plex-item [colors]="misColores" ...>
```
=> plex item custom color

cypress/integration/label.js, src/demo/app/label/label.component.ts, src/demo/app/label/label.html, src/lib/css/plex-label.scss, src/lib/label/label.component.ts
Extiende componente permitiendo albergar dato alfanumérico en lugar de icono
- El dato mantiene el tratamiento visual del icono (hereda border y sizes).
- El dato acompaña la direccionalidad del plex-label ('row' como 'column').
- Se procura que si hay icono, no hay dato alfanumérico y viceversa.
**Next:** en un [PR futuro](https://github.com/andes/plex/tree/PLEX-64) se incluyen las líneas que conectan los distinto items que conforman una conjunto de labels _(ej.: línea de tiempo)_.
=> feat(plex-label): permite caracteres en lugar de icono

src/lib/css/plex-wrapper.scss, src/lib/wrapper/wrapper.component.ts
Dotar al componente de la capacidad de detectar y notificar cuando un filtro oculto está activo.
- Se agrega el @Input 'activeFilters' que en valor 'true' (y al estar replegado el plex-wrapper) posibilita la visualización de la alerta (plex-hint).
=> feat(plex-wrapper): notifica filtros activos ocultos

cypress/integration/button.js, src/demo/app/button/button.component.ts, src/demo/app/button/button.html, src/lib/button/button.component.spec.ts, src/lib/button/button.component.ts, src/lib/core/network-loading.service.ts, src/lib/core/service.ts, src/lib/datetime/datetime.component.spec.ts, src/lib/dropdown/dropdown.component.ts
Agrega propiedad **autodisabled** a plex-button, un botón marcado con esta propiedad se pone automáticamente en disabled si hay un request del tipo POST, PUT, PATCH, DELETE en progreso. (uno o varios). 
El único detalle que se observa es que si en la pantalla hay dos botones diferentes con esta propiedad los dos se ponen automáticamente en disabled. Indistintamente el que se haya apretado. De todas manera debe ser un caso poco usual.
=> feat(plex-button): autodisabled prop

src/demo/app/datetime/datetime.component.ts, src/demo/app/datetime/datetime.html, src/lib/datetime/datetime.component.ts, src/lib/text/text.component.ts
Agrega @Output en plex-text y plex-datetime indicando que el usuario esta escribiendo. Útil cuando el elemento tiene la propiedad debounce pero se quiere deshabilitar un botón apenas arranca a escribir hasta que se ejecute el GET a la base de datos. 
Con la propiedad debounce el evento Change se pospone dando unos milisegundo de changui al usuario de apretar algo.
=> Plex text typing

src/demo/app/accordion/accordion.component.ts, src/demo/app/accordion/accordion.html, src/lib/css/plex-accordion.scss
**Problema**
Existe superposición al desplegarse un plex-select alojado dentro de un plex-accordion con los cabezales de otros elementos.
https://user-images.githubusercontent.com/5895886/103659558-501ab080-4f4b-11eb-8437-e31e9144cbcd.mp4
**Solución**
Se agrega la propiedad z-index con valor '1' al panel desplegado del accordion de modo que su contenido quede por encima del resto de los elementos.
https://user-images.githubusercontent.com/5895886/103659750-8ce6a780-4f4b-11eb-9e49-01c74567a706.mp4
**Plus**
Se modifica demo de accordion reproduciendo la situación de uso
=> fix(plex-accordion): resuelve superposición al alojar componentes desplegables

src/demo/app/button/button.html, src/lib/badge/badge.component.ts, src/lib/css/plex-badge.scss
**Problema**
Se debe agregar un bloque de código y diversas clases manualmente para lograr incorporar un número junto al badge.
**Solución**
Se agrega un selector [dato] en el template y las clases correspondientes directamente en la hoja de estilo del componente.
=> feat(plex-badge): agrega selector para dato numérico

src/demo/app/table/table.html, src/lib/css/plex-table.scss, src/lib/table/table-column-dropdown.component.ts
- Se corrige clase selected y selectable.
- Se corrige efecto indeseado en cabezal al aparecer las flechitas al lado de cada `<th>`.
- Se baja opacidad del cabezal fijo al scrollear.
**Next:**
- Todas las columnas visibles por default
- Posibilidad de fijar plex-title embebido en plex-table (selector 'main')
https://user-images.githubusercontent.com/5895886/104818526-e5992880-5806-11eb-9dfe-03602ce4e014.mp4
=> fix(plex-table): corrige clases selected/selectable

src/demo/app/card/card.component.html, src/demo/app/card/card.component.ts, src/lib/card/card.component.ts, src/lib/css/classes.scss, src/lib/css/plex-card.scss, src/lib/css/plex-grid.scss, src/lib/directives/span.directive.ts
- Se extiende encolumnado a 12 columnas (grid-template-columns).
- Se extienden valores de directiva Span a 12 (grid-column).
**Caso de uso**
División interna de paneles del layout.
=> feat(plex-grid): extiende encolumnado y spanDirective

src/demo/app/phone/phone.component.ts, src/demo/app/phone/phone.html, src/lib/phone/phone.component.ts
A veces se necesita crear modelos dinamicamente, para lo cual es necesario que los componentes estén atentos a esta situación, no generando mensajes inesperados o errores.
=> fix(plex-phone): evita mostrar "undefined" si model (aun) no existe

src/lib/css/plex-visualizador.scss, src/lib/visualizador/visualizador.component.ts
**Problema**
Las flechas para navegar entre las imágenes del lightbox se encuentran relativas a la imagen maximizada, generando que su ubicación varíe según el ancho de la imagen.
**Solución**
Se agrega la directiva 'justify' para distribuir de manera uniforme las flechas y la imagen.
Adicionalmente, se agrega padding al lightbox para evitar que la navegación quede en los extremos de la pantalla.
=> fix(plex-visualizador): corrige posicion flechas prev/next

src/lib/css/plex-wrapper.scss
**Task**
https://proyectos.andes.gob.ar/browse/PLEX-230
**Problema**
Propiedades del plex-wrapper son heredadas por ciertos componentes que aloja.
**Solución**
Se restringe la aplicación de las propiedades sólo al primer section anidado en el plex-wrapper de modo que las hereden los componentes correspondientes (los que constituyen los filtros).
=> fix(plex-wrapper): corrige herencia indeseada de propiedades

src/demo/app/button/button.html, src/lib/button/button.component.ts
[PLEX-248](https://proyectos.andes.gob.ar/browse/PLEX-248)
**Contexto**
Actualmente, diversos componente PLEX carecen de éste atributo, imposibilitando ser percibidos por lectores de pantalla.
**Problema**
Dificultad para brindar información en botones con ausencia de texto (acciones iconográficas).
**Solución**
Se agrega @Input() ariaLabel a nivel componente y se pasa el string a un atributo aria-label a nivel HTML.
=> feat(plex-button): agrega atributo aria-label

src/demo/app/grid/grid.component.html, src/demo/app/grid/grid.component.ts, src/lib/css/plex-grid.scss, src/lib/grid/grid.component.ts
Task: https://proyectos.andes.gob.ar/browse/PLEX-243
- Se evita herencia indeseada de atributos propios de la grilla (ocurría al anidar una plex-grid dentro de otra plex-grid, si la segunda no tenía seteado un valor en sus atributos, tomaba los del padre).
- Se elimina la clase 'text-transform: capitalize' (actualmente heredada por todos los componentes que aloja la grilla).
- Se agrega la posibilidad de setear la cantidad de columnas dependiendo del breakpoint (colsSm - colsMd - colsLg).
- Se reemplazan clases modificadoras por mixins.
- Se modifica el nombre de la clase 'size' para evitar colisión con clases de directiva [responsive].
- Se declaran los atributos desde el componente (y no desde el css).
**Plus:**
Se actualiza demo del componente
=> feat(plex-grid): refactoriza y extiende componente

src/demo/app/templates/componentes/plex-modal-template/plex-modal-template.html, src/lib/css/plex-box.scss, src/lib/css/plex-modal.scss, src/lib/modal/modal.component.ts
- Algunas clases de invert se estaban filtrando dentro de otros componentes, generando situaciones indeseadas.
- Se actualizó demo en `/modal` confirmando esta funcionalidad
=> fix(plex-modal): se evita herencia desde invert

src/lib/css/layout.scss
**Problema**
Se utilizaba el selector `[class^="col-"]` por lo que al inyectarse una clase antes de la clase `col-`, el resto de las clases anidadas quedaban sin efecto.
**Solución** 
Se modifica el selector por `[class*="col-"]` preservando las restricciones pertinentes.
**Sugerencia**
Testear en la app apuntando a esta rama
=> fix(plex-layout): permite funcionamiento de resizable

src/lib/css/plex-item.scss
**Task**
[https://proyectos.andes.gob.ar/browse/PLEX-249](https://proyectos.andes.gob.ar/browse/PLEX-249)
**Problema**
En contextos de menor dimensión (mobile, sidebars) tanto los `plex-badge ` como `plex-button` quedan en una sóla línea, de modo que la convivencia entre varios elementos tiende a desbordarse de la pantalla.
**Solución**
Se agrega la propiedad 'flex-wrap' con valor 'wrap' al estar en contextos de menor dimensión (a través de la directiva responsive).
=> fix(plex-item): botonera con wrap en responsive

src/demo/app/card/card.component.html, src/demo/app/card/card.component.ts, src/demo/app/directives/componentes/align/align.html, src/demo/app/grid/grid.component.html, src/lib/card/card.component.ts, src/lib/css/classes.scss, src/lib/css/mixins/_contrast.scss, src/lib/css/plex-card.scss
- Se refactoriza la hoja de estilos incorporando mixins y custom-properties que permiten simplificar los cálculos en las variantes cromáticas (brillo y saturación)
- Se resuelve tipología custom outlined desde el .ts (como opción al método darken/lighten)
- Se incluye un mixin para calcular colores accesibles (optimiza contrastes)
- Se actualiza la demo del componente
=> feat(plex-card): refactor + tipología outlined

cypress/integration/tabs.js, src/demo/app/tabs/tabs.html, src/lib/tabs/tab.component.ts, src/lib/tabs/tabs.component.ts
**1. Se agregan roles correspondientes**
⦁ `role="tablist"` al contenedor de las tabs (otorga semántica al elemento, detectando la cantidad de pestañas)
⦁ `role="tab"` al elementos tabeable de la pestaña (identifica al `<li>` como pestaña)
⦁ `role="presentation"` para que el screen reader ignore la semantica de la `<ul>` (que no diga lista, que diga lista de pestañas)
**2. Se agregan arias correspondientes**
⦁ aria-selected _(screen reader menciona la pestaña activa)_
⦁ aria-label _(screen reader menciona descripción del título y botones "cerrar")_
**3. Se agrega funcionalidad accesible por teclado**
⦁ focusable con tab
⦁ navegación con arrows _(flechitas)_
**Plus:** se agrega test de cypress al componente
**Para testear:** 
Tabear hasta llegar a las tabs y navegarlas mediante flechas. …
=> plex-tabs: agrega atributos de accesibilidad

src/demo/app/button/button.html, src/lib/css/plex-accordion.scss, src/lib/css/plex-badge.scss, src/lib/css/plex-help.scss, src/lib/css/plex-item.scss
**Task**
https://proyectos.andes.gob.ar/browse/PLEX-255
**Problemas**
1. plex-badge con button incorporado se pierde en estado :hover + separación del botón respecto al badge.
2. En contexto de plex-help, se perciben desalineados los plex-buttons en relación al resto de los elementos.
**Soluciones**
1. Se quita propiedad mix-blend del estado :hover del plex-button incorporados dentro de plex-badges.
2. Se remueve la propiedad top: 1px, existente en estilos de buttons presentes en botonera del plex-item.
**Plus**
Se resuelve herencia indeseada en plex-accordion
https://proyectos.andes.gob.ar/browse/PLEX-282
=> fix(plex-badge): resuelve hover en invert + alineación badge-btn

src/lib/accordion/panel.component.ts, src/lib/accordion/pl-accordion.directive.ts, src/lib/module.ts
https://proyectos.andes.gob.ar/browse/PLEX-291
Se agrega nueva directiva plAccordion
1. Se agregó la nueva directiva plAccordion que renderiza el contenido una vez que se encuentra activa. Se puede enviar a la una cantidad de tiempo para que se retrase la carga aunque no este activo el panel.
=> Plex-Accordion: nueva directiva plAccordion

src/demo/app/label/label.component.ts, src/demo/app/label/label.html, src/lib/css/plex-label.scss, src/lib/label/label.component.ts
**Tarea**
https://proyectos.andes.gob.ar/browse/PLEX-226
**Situación de uso**
Diferenciar elementos de un listado
**Criterio de aceptación**
El color se configura mediante el selector de la propiedad [color].
Que el color se apliqué sólo al icono.
**Plus**
Se actualiza demo con caso de uso (ver adjunto).
=> feat(plex-label): posibilita custom-colors

cypress/integration/label.js, src/demo/app/card/card.component.html, src/lib/card/card.component.ts, src/lib/css/mixins/_contrast.scss, src/lib/css/mixins/cardBackground.scss, src/lib/css/plex-card.scss, src/lib/css/plex-label.scss, src/lib/label/label.component.ts
**Objetivo:**
- Plex-card tabeables (incorporación de tabindex en el template del componente)
- Plex-label identificables como texto (cambia `<span>` por `<p>`)
**Plus**
Se fixea conflicto de color en estado hover de cards outlined.
**Test**
Navegar a demos de componentes [plex-label](http://localhost:4200/label) y [plex-card](http://localhost:4200/card) con screen reader ([NVDA](https://nvda.es/))
=> feat(plex-card): tabindex + refactor html plex-label

cypress/integration/directiva-hint.js, cypress/integration/select.js, src/lib/css/hint.scss, src/lib/css/plex-hint.scss, src/lib/hint/hint.component.ts, src/lib/styles.scss
Se encontró que el hint aunque es funcional en mobile, al usar un tag `<a>` algunos navegadores interpretan que el usuario quiere abrir un link en una nueva pestaña. 
Se reemplazó por un tag `<span>` con `tabindex="0"`
```html
<span tabindex="0" *ngIf="position && content" class="hint-container detach-{{detach}}" [matTooltip]="content" [matTooltipPosition]="position" [matTooltipShowDelay]="0">
<plex-icon class="hint {{ hintType }}" [name]="hintIcon" size="xs" type="light"></plex-icon>
</span>
```
=> fix(hint): accesible en mobile

src/demo/app/table/table.ts, src/lib/table/columns.directive.ts
Una columna con la propiedad `sortable: false` provoca un error interno en el componente porque no hay comprobación sobre esta propiedad, ya que se intenta llamar a la función `sort` del componente.
=> fix(plex-table): implementa sorteable: false

src/demo/app/help/help.html, src/lib/css/plex-help.scss, src/lib/help/help.component.ts
- `<plex-help cardSize="auto" ...>` no genera un scroll, se adapta al alto de la pantalla
- `<plex-help [btnType]="PlexType" ...>` permite usar colores de botón help según la paleta Andes
=> Mejoras en plex-help (alto automático y color types)

src/demo/app/home/home.component.ts, src/demo/app/home/home.html, src/lib/title/title.component.ts
Implementa navegación hacia atrás en `plex-title`.
Funciona usando un Output `back`, por ejemplo: 
```html
<plex-title main justify titulo="Gestor de agendas" (back)="back()"> ... </plex-title>
```
```typescript
public back() {
// ir atrás
}
```
=> PLEX-309: Navegación hacia atrás en plex-title

cypress/integration/menu.js, src/demo/app/app.component.ts, src/demo/app/radio/radio.html, src/lib/css/plex-radio.scss
- Implementa visualización invert (sidebar)
- Se actualiza la demo
=> plex-radio invert

src/lib/text/text.component.ts
https://proyectos.andes.gob.ar/browse/PLEX-129
- Se puede agregar en los plex-text con multiline="true" el atributo **rows** para darle una altura fija. El valor en rows es guardado se toma con la unidad de medida em (Por ejemplo, rows="5" son 5em) -> **1em = 16px**
- Si no posee el atributo rows, por defecto tiene un alto de 4em (64px).
=> PLEX-TEXT - agrega rows en plex-text multiline

src/lib/css/plex-radio.scss, src/lib/radio/radio.component.ts
**Requerimiento**
https://proyectos.andes.gob.ar/browse/PLEX-264
**Funcionalidad desarrollada**
1.  Se cambia white-space: nowrap de material por white-space:normal, para que el texto se ajuste cuando sea necesario
2. Se agrega overflow-wrap: anywhere para que las palabras largas vayan hacia abajo si desbordan el contenedor.
**Para revisar**
- Por ejemplo modificar el label de las opciones de radio.component.ts, poner uno bastante extenso para ver el resultado.
=> PLEX-RADIO - Quita nowrap 

src/lib/help/help.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-326
1. Se realiza el cierre automático de plex-help cuando se realiza scroll sobre el componente padre para evitar el mal posicionamiento en pantalla.
=> PLEX: Control de cierre de plex-help cuando hay scroll

src/lib/css/plex-table.scss, src/lib/table/table.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-327
1. Se implementa selector de opacidad para plex-table head, con valores múltiples de 10 entre 0 y 100.
2. Se utiliza la prop headOpacity para asignar el valor de opacidad.
3. La opacidad se aplica tanto a plex-table tradicional y en sidebar.
=> Plex - Selector de transparencias en table head

src/lib/help/help.component.ts, src/lib/help/services/help.service.ts, src/lib/module.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-323
1. Se implementa una cache de datos para mantener una única instancia de plex-help abierta. Se controla mediante un id autogenerado si el plex-help que se abre es el actual o uno nuevo.
=> PLEX -  Evitar aperturas de plex-help simultáneas

src/demo/app/select/select.component.ts, src/demo/app/select/select.html, src/lib/select/select.component.ts
- Implementa un `@Input` que acepta un array de strings indicando qué datos del set que usa el `plex-select` se quieren mostrar como datos extra.
- dataset: 
```typescript
[{
id: 1,
nombre: 'PEDRO',
apellido: 'PEREZ',
documento: '123456789'
}]
```
- uso HTML: 
```html
<plex-select [(ngModel)]="modelo2.selectMultiple" [multiple]="true" name="selectmultiple"
(getData)="loadData($event)" label="Múltiple con llamada a la API"
[readonly]="modelo2.soloLectura" placeholder="Ingrese un país" labelField="nombre+' '+apellido"
[extraFields]="['documento']">
</plex-select>
```
https://user-images.githubusercontent.com/11394455/146250894-2a7f2912-412d-4253-aed0-fb7eb2db78b4.mov
=> Datos extra en plex-select

src/lib/css/plex-bool.scss
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-342
1. Modifica estilos en plex-bool para quitar overflow en checkbox
=> PLEX-BOOL - Corregir overflow en checkbox

src/lib/text/text.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-348
Implementa fix para evitar borrado de saltos de línea luego de cargar contenido HTML a plex-text
=> PLEX-TEXT - Repara error de vista html en plex-text

cypress/integration/card.js, src/demo/app/text/text.component.ts, src/demo/app/text/text.html, src/lib/text/text.component.ts, src/lib/validation-messages/validation-messages.component.ts
Requerimiento
https://proyectos.andes.gob.ar/browse/PLEX-356
Implementa param -customValidation- para pasar una función validadora junto con un mensaje, que permita mostrar el error tras no cumplir la condicion validadora.
=> PLEX-TEXT - Implementa validación personalizada
